name: C/C++ CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Autogen and Configure
        run: |
          ./autogen.sh
          ./configure
      - name: Make
        run: make
      - name: Make Check
        run: make check
      - name: Make Distcheck
        run: make distcheck
